name: "Node.js NPX"
description: "Persistent Node.js, npm and NPX environment for Home Assistant OS"
version: "1.2.0"
slug: "nodejs_npx"
init: false
arch:
  - amd64
startup: services
boot: auto
map:
  - addon_config:rw
options:
  command: ""
schema:
  command: str
