name: "Node.js NPX"
description: "Persistent Node.js, npm and NPX environment for Home Assistant OS"
version: "1.5.4"
slug: "nodejs_npx"
init: false
homeassistant_api: true
hassio_api: true
arch:
  - amd64
startup: services
boot: auto
map:
  - addon_config:rw
options:
  command: ""
  package: ""
  version: "latest"
  arguments: ""
  auto_update: false
schema:
  command: str
  package: str?
  version: str?
  arguments: str?
  auto_update: bool?
